// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: api.proto

package api

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NewsfeedConfiguratorClient is the client API for NewsfeedConfigurator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewsfeedConfiguratorClient interface {
	AddUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*UserId, error)
	GetUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*User, error)
	UpdateUserFilter(ctx context.Context, in *User, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*empty.Empty, error)
	AddSource(ctx context.Context, in *AddSourceRequest, opts ...grpc.CallOption) (*SourceId, error)
	GetSource(ctx context.Context, in *SourceId, opts ...grpc.CallOption) (*Source, error)
	GetUserSources(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*Sources, error)
	UpdateSourceName(ctx context.Context, in *UpdateSourceNameRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteSource(ctx context.Context, in *SourceId, opts ...grpc.CallOption) (*empty.Empty, error)
}

type newsfeedConfiguratorClient struct {
	cc grpc.ClientConnInterface
}

func NewNewsfeedConfiguratorClient(cc grpc.ClientConnInterface) NewsfeedConfiguratorClient {
	return &newsfeedConfiguratorClient{cc}
}

func (c *newsfeedConfiguratorClient) AddUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*UserId, error) {
	out := new(UserId)
	err := c.cc.Invoke(ctx, "/api.NewsfeedConfigurator/addUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsfeedConfiguratorClient) GetUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/api.NewsfeedConfigurator/getUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsfeedConfiguratorClient) UpdateUserFilter(ctx context.Context, in *User, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.NewsfeedConfigurator/updateUserFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsfeedConfiguratorClient) DeleteUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.NewsfeedConfigurator/deleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsfeedConfiguratorClient) AddSource(ctx context.Context, in *AddSourceRequest, opts ...grpc.CallOption) (*SourceId, error) {
	out := new(SourceId)
	err := c.cc.Invoke(ctx, "/api.NewsfeedConfigurator/addSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsfeedConfiguratorClient) GetSource(ctx context.Context, in *SourceId, opts ...grpc.CallOption) (*Source, error) {
	out := new(Source)
	err := c.cc.Invoke(ctx, "/api.NewsfeedConfigurator/getSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsfeedConfiguratorClient) GetUserSources(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*Sources, error) {
	out := new(Sources)
	err := c.cc.Invoke(ctx, "/api.NewsfeedConfigurator/getUserSources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsfeedConfiguratorClient) UpdateSourceName(ctx context.Context, in *UpdateSourceNameRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.NewsfeedConfigurator/updateSourceName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsfeedConfiguratorClient) DeleteSource(ctx context.Context, in *SourceId, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.NewsfeedConfigurator/deleteSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewsfeedConfiguratorServer is the server API for NewsfeedConfigurator service.
// All implementations must embed UnimplementedNewsfeedConfiguratorServer
// for forward compatibility
type NewsfeedConfiguratorServer interface {
	AddUser(context.Context, *UserId) (*UserId, error)
	GetUser(context.Context, *UserId) (*User, error)
	UpdateUserFilter(context.Context, *User) (*empty.Empty, error)
	DeleteUser(context.Context, *UserId) (*empty.Empty, error)
	AddSource(context.Context, *AddSourceRequest) (*SourceId, error)
	GetSource(context.Context, *SourceId) (*Source, error)
	GetUserSources(context.Context, *UserId) (*Sources, error)
	UpdateSourceName(context.Context, *UpdateSourceNameRequest) (*empty.Empty, error)
	DeleteSource(context.Context, *SourceId) (*empty.Empty, error)
	mustEmbedUnimplementedNewsfeedConfiguratorServer()
}

// UnimplementedNewsfeedConfiguratorServer must be embedded to have forward compatible implementations.
type UnimplementedNewsfeedConfiguratorServer struct {
}

func (UnimplementedNewsfeedConfiguratorServer) AddUser(context.Context, *UserId) (*UserId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedNewsfeedConfiguratorServer) GetUser(context.Context, *UserId) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedNewsfeedConfiguratorServer) UpdateUserFilter(context.Context, *User) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserFilter not implemented")
}
func (UnimplementedNewsfeedConfiguratorServer) DeleteUser(context.Context, *UserId) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedNewsfeedConfiguratorServer) AddSource(context.Context, *AddSourceRequest) (*SourceId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSource not implemented")
}
func (UnimplementedNewsfeedConfiguratorServer) GetSource(context.Context, *SourceId) (*Source, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSource not implemented")
}
func (UnimplementedNewsfeedConfiguratorServer) GetUserSources(context.Context, *UserId) (*Sources, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSources not implemented")
}
func (UnimplementedNewsfeedConfiguratorServer) UpdateSourceName(context.Context, *UpdateSourceNameRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSourceName not implemented")
}
func (UnimplementedNewsfeedConfiguratorServer) DeleteSource(context.Context, *SourceId) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSource not implemented")
}
func (UnimplementedNewsfeedConfiguratorServer) mustEmbedUnimplementedNewsfeedConfiguratorServer() {}

// UnsafeNewsfeedConfiguratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewsfeedConfiguratorServer will
// result in compilation errors.
type UnsafeNewsfeedConfiguratorServer interface {
	mustEmbedUnimplementedNewsfeedConfiguratorServer()
}

func RegisterNewsfeedConfiguratorServer(s grpc.ServiceRegistrar, srv NewsfeedConfiguratorServer) {
	s.RegisterService(&NewsfeedConfigurator_ServiceDesc, srv)
}

func _NewsfeedConfigurator_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsfeedConfiguratorServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.NewsfeedConfigurator/addUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsfeedConfiguratorServer).AddUser(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsfeedConfigurator_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsfeedConfiguratorServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.NewsfeedConfigurator/getUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsfeedConfiguratorServer).GetUser(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsfeedConfigurator_UpdateUserFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsfeedConfiguratorServer).UpdateUserFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.NewsfeedConfigurator/updateUserFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsfeedConfiguratorServer).UpdateUserFilter(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsfeedConfigurator_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsfeedConfiguratorServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.NewsfeedConfigurator/deleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsfeedConfiguratorServer).DeleteUser(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsfeedConfigurator_AddSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsfeedConfiguratorServer).AddSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.NewsfeedConfigurator/addSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsfeedConfiguratorServer).AddSource(ctx, req.(*AddSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsfeedConfigurator_GetSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsfeedConfiguratorServer).GetSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.NewsfeedConfigurator/getSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsfeedConfiguratorServer).GetSource(ctx, req.(*SourceId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsfeedConfigurator_GetUserSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsfeedConfiguratorServer).GetUserSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.NewsfeedConfigurator/getUserSources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsfeedConfiguratorServer).GetUserSources(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsfeedConfigurator_UpdateSourceName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSourceNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsfeedConfiguratorServer).UpdateSourceName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.NewsfeedConfigurator/updateSourceName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsfeedConfiguratorServer).UpdateSourceName(ctx, req.(*UpdateSourceNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsfeedConfigurator_DeleteSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsfeedConfiguratorServer).DeleteSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.NewsfeedConfigurator/deleteSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsfeedConfiguratorServer).DeleteSource(ctx, req.(*SourceId))
	}
	return interceptor(ctx, in, info, handler)
}

// NewsfeedConfigurator_ServiceDesc is the grpc.ServiceDesc for NewsfeedConfigurator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NewsfeedConfigurator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.NewsfeedConfigurator",
	HandlerType: (*NewsfeedConfiguratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addUser",
			Handler:    _NewsfeedConfigurator_AddUser_Handler,
		},
		{
			MethodName: "getUser",
			Handler:    _NewsfeedConfigurator_GetUser_Handler,
		},
		{
			MethodName: "updateUserFilter",
			Handler:    _NewsfeedConfigurator_UpdateUserFilter_Handler,
		},
		{
			MethodName: "deleteUser",
			Handler:    _NewsfeedConfigurator_DeleteUser_Handler,
		},
		{
			MethodName: "addSource",
			Handler:    _NewsfeedConfigurator_AddSource_Handler,
		},
		{
			MethodName: "getSource",
			Handler:    _NewsfeedConfigurator_GetSource_Handler,
		},
		{
			MethodName: "getUserSources",
			Handler:    _NewsfeedConfigurator_GetUserSources_Handler,
		},
		{
			MethodName: "updateSourceName",
			Handler:    _NewsfeedConfigurator_UpdateSourceName_Handler,
		},
		{
			MethodName: "deleteSource",
			Handler:    _NewsfeedConfigurator_DeleteSource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
